<fieldset id="journal-freeform-fieldset" class="rows">
    <legend>Kausijulkaisun tiedot</legend>
    <ol id="journal-freeform-fields">
        <li>
            <label for="title">Nimeke:</label>
            <input type="text" name="title" id="title" value="[% whole.value.other.title %]" />
        </li>
        <li>
            <label for="volume">Volyymi:</label>
            <input type="text" name="volume" id="volume" value="[% whole.value.other.volume %]" />
        </li>
        <li>
            <label for="issue">Numero:</label>
            <input type="text" name="issue" id="issue" value="[% whole.value.other.issue %]" />
        </li>
        <li>
            <label for="year">Vuosi:</label>
            <input type="text" name="year" id="year" value="[% whole.value.other.year %]" />
        </li>
        <li>
            <label for="issn">ISSN:</label>
            <input type="text" name="issn" id="issn" value="[% whole.value.other.issn %]" />
        </li>
        <li>
            <label for="doi">DOI:</label>
            <input type="text" name="doi" id="doi" value="[% whole.value.other.doi %]" />
        </li>
    </ol>
</fieldset>
